controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

calculator_index:
    path: /calculator
    controller: App\Controller\CalculatorController::index
